# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 473094f53ec980f30d3a73abfad7f291d6213da8f197f23bb87717b3c6234337b1b18517c0c9a05693542cd177f255c6dbee2ae0945628dc86c93d3da4333e1e

test:
  secret_key_base: a819925ed694547baac62d80aeab16dc1e2b3f537bcb861a7a93d6d8302ef2fa8ec5ba5eb4ef09b8a77e5843e50ab5289c1b3cd7695f8ba2903330a064cd261c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
